name: Site Deploy (S3 Sync + CF Invalidate)

on:
  push:
    branches: [ main ]
    paths:
      - "site/**"
      - ".github/workflows/site-deploy.yml"

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  S3_BUCKET: ${{ vars.S3_BUCKET }}
  CF_DISTRIBUTION_ID: ${{ vars.CF_DISTRIBUTION_ID }}

concurrency:
  group: site-deploy
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.SYNC_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Dry-run to check changes
        id: diff
        shell: bash
        run: |
          set -euo pipefail
          # 変更があるかどうかだけ判定（出力を artifact にも使えるよう保存）
          aws s3 sync ./site "s3://${S3_BUCKET}/" \
            --delete --dryrun \
            --exclude ".git/*" --exclude ".github/*" \
            --exclude "*.tf" --exclude "*.tfvars" --exclude "*.tfstate*" \
            | tee /tmp/s3_diff.txt
          if [ -s /tmp/s3_diff.txt ]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          else
            echo "changed=false" >> "$GITHUB_OUTPUT"
          fi

      - name: S3 Sync (apply when changed)
        if: steps.diff.outputs.changed == 'true'
        shell: bash
        run: |
          set -euo pipefail
          aws s3 sync ./site "s3://${S3_BUCKET}/" --delete \
            --exclude ".git/*" --exclude ".github/*" \
            --exclude "*.tf" --exclude "*.tfvars" --exclude "*.tfstate*"

      - name: CloudFront Invalidation (only when changed)
        if: steps.diff.outputs.changed == 'true'
        run: |
          aws cloudfront create-invalidation \
            --distribution-id "${CF_DISTRIBUTION_ID}" \
            --paths "/*"

      - name: Skip notice (no changes)
        if: steps.diff.outputs.changed != 'true'
        run: echo "No content changes. Skipping sync & invalidation."