name: Terraform (S3+CloudFront OAC)

on:
  push:
    branches: [main]
    paths:
      - "**/*.tf"
      - "**/*.tfvars"
      - ".github/workflows/terraform.yml"
  pull_request:
    branches: [main]
    paths:
      - "**/*.tf"
      - "**/*.tfvars"

permissions:
  id-token: write
  contents: read

jobs:
  tf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.TF_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: WhoAmI (debug)
        run: aws sts get-caller-identity

      - name: Export TF vars (bucket_name etc)
        run: |
          echo "TF_VAR_bucket_name=${{ vars.S3_BUCKET }}" >> $GITHUB_ENV  

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan (PR only)
        if: github.event_name == 'pull_request'
        run: terraform plan -no-color -input=false

      - name: Terraform Plan (push)
        if: github.event_name == 'push'
        run: terraform plan -no-color -input=false

      - name: Terraform Apply (push only)
        if: github.event_name == 'push'
        run: terraform apply -auto-approve -input=false -no-color